export const ICONS = {
  userTurn: ">",
  assistantTurn: "●",
  assistantLabel: "Custom-PI",
  success: "●",
  error: "●",
  waiting: "◌",
  running: "●",
  spinnerDots: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"],
  checkmark: "✓",
  cross: "✗",
  arrowUp: "↑",
  arrowDown: "↓",
  bullet: "•",
  star: "★",
  sparkle: "✦",
  bolt: "⚡",
  separator: "─",
  diff: "diff",
};
